"""
src/email_sender.py  —  Send the MIS report via email
Attaches the Excel report and includes a plain-text AI summary in the body.
Works with Gmail (App Password), Outlook, and any SMTP provider.
"""

import os
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text      import MIMEText
from email.mime.base      import MIMEBase
from email                import encoders
from datetime             import datetime
import config


def _build_email_body(kpis: dict, commentary: str, risk_flags: list) -> str:
    """Build a clean plain-text email body."""
    flag_lines = "\n".join([
        f"  • [{f['severity'].upper()}] {f['flag']}: {f['detail']}"
        for f in risk_flags
    ]) if risk_flags else "  • No critical flags this period."

    return f"""
{'='*60}
{config.COMPANY_NAME.upper()} — WEEKLY MIS REPORT
Generated: {datetime.today().strftime('%d %b %Y, %H:%M')}
Period:    {kpis.get('period_start','N/A')} to {kpis.get('period_end','N/A')}
{'='*60}

KEY METRICS AT A GLANCE
-----------------------
  Revenue:          £{kpis.get('total_revenue', 0):>12,.0f}
  Gross Margin:     {kpis.get('gross_margin_pct', 0):>11.1f}%
  Net Profit:       £{kpis.get('net_profit', 0):>12,.0f}
  Budget Variance:  {kpis.get('budget_variance_pct', 0):>+11.1f}%
  MoM Revenue Δ:    {kpis.get('mom_revenue_change_pct', 0):>+11.1f}%
  SLA Breach Rate:  {kpis.get('sla_breach_rate_pct', 0):>11.1f}%

RISK FLAGS
----------
{flag_lines}

AI EXECUTIVE COMMENTARY
-----------------------
{commentary}

{'='*60}
Full report is attached. Open in Excel for department breakdown,
P&L detail, anomaly analysis, and Power BI-ready trend data.
{'='*60}

This report was auto-generated by the MIS Report Generator.
Do not reply to this email.
""".strip()


def _build_html_body(kpis: dict, commentary: str, risk_flags: list) -> str:
    """Build an HTML email body with simple table formatting."""
    flag_rows = "".join([
        f"<tr><td style='padding:4px 8px;color:{'#A32D2D' if f['severity']=='high' else '#633806'}'>"
        f"<b>[{f['severity'].upper()}]</b> {f['flag']}</td>"
        f"<td style='padding:4px 8px'>{f['detail']}</td></tr>"
        for f in risk_flags
    ]) if risk_flags else "<tr><td colspan='2' style='padding:4px 8px;color:#085041'>No critical flags this period.</td></tr>"

    variance_color = "#A32D2D" if kpis.get("budget_variance_pct", 0) < 0 else "#085041"
    mom_color      = "#A32D2D" if kpis.get("mom_revenue_change_pct", 0) < 0 else "#085041"

    return f"""
<html><body style="font-family:Calibri,Arial,sans-serif;color:#1a1a1a;max-width:680px;margin:0 auto">

<div style="background:#085041;color:#fff;padding:18px 24px;border-radius:8px 8px 0 0">
  <h2 style="margin:0;font-size:20px">{config.COMPANY_NAME} — Weekly MIS Report</h2>
  <p style="margin:6px 0 0;font-size:13px;opacity:0.8">
    Period: {kpis.get('period_start','N/A')} to {kpis.get('period_end','N/A')} &nbsp;|&nbsp;
    Generated: {datetime.today().strftime('%d %b %Y')}
  </p>
</div>

<div style="padding:20px 24px;background:#f9f9f7;border:1px solid #D3D1C7">

  <h3 style="color:#085041;margin:0 0 12px">Key Metrics</h3>
  <table style="width:100%;border-collapse:collapse;font-size:14px">
    <tr>
      <td style="padding:8px;background:#E1F5EE;border-radius:6px;text-align:center">
        <div style="font-size:11px;color:#444">Total Revenue</div>
        <div style="font-size:18px;font-weight:bold">£{kpis.get('total_revenue',0):,.0f}</div>
      </td>
      <td style="width:8px"></td>
      <td style="padding:8px;background:#E1F5EE;border-radius:6px;text-align:center">
        <div style="font-size:11px;color:#444">Gross Margin</div>
        <div style="font-size:18px;font-weight:bold">{kpis.get('gross_margin_pct',0):.1f}%</div>
      </td>
      <td style="width:8px"></td>
      <td style="padding:8px;background:#E1F5EE;border-radius:6px;text-align:center">
        <div style="font-size:11px;color:#444">Net Profit</div>
        <div style="font-size:18px;font-weight:bold">£{kpis.get('net_profit',0):,.0f}</div>
      </td>
      <td style="width:8px"></td>
      <td style="padding:8px;background:#FAEEDA;border-radius:6px;text-align:center">
        <div style="font-size:11px;color:#444">Budget Variance</div>
        <div style="font-size:18px;font-weight:bold;color:{variance_color}">{kpis.get('budget_variance_pct',0):+.1f}%</div>
      </td>
      <td style="width:8px"></td>
      <td style="padding:8px;background:#FAEEDA;border-radius:6px;text-align:center">
        <div style="font-size:11px;color:#444">MoM Revenue</div>
        <div style="font-size:18px;font-weight:bold;color:{mom_color}">{kpis.get('mom_revenue_change_pct',0):+.1f}%</div>
      </td>
    </tr>
  </table>

  <h3 style="color:#085041;margin:20px 0 8px">Risk Flags</h3>
  <table style="width:100%;border-collapse:collapse;font-size:13px;border:1px solid #D3D1C7">
    {flag_rows}
  </table>

  <h3 style="color:#085041;margin:20px 0 8px">AI Executive Commentary</h3>
  <div style="background:#FFFEF9;border-left:4px solid #1D9E75;padding:14px 16px;
              font-size:13px;line-height:1.7;border-radius:0 6px 6px 0">
    {commentary.replace(chr(10), '<br>')}
  </div>

  <p style="font-size:12px;color:#888;margin-top:24px">
    Full report is attached. Open in Excel for department breakdown, P&L detail,
    anomaly analysis, and Power BI-ready trend data.
  </p>
</div>

<div style="background:#F1EFE8;padding:10px 24px;border-radius:0 0 8px 8px;
            font-size:11px;color:#888;text-align:center">
  Auto-generated by MIS Report Generator &nbsp;|&nbsp; Do not reply to this email
</div>

</body></html>
"""


def send_report(
    kpis:            dict,
    commentary:      str,
    risk_flags:      list,
    attachment_path: str,
    recipients:      list = None,
    subject:         str  = None,
) -> bool:
    """
    Send the MIS report email with Excel attachment.
    Returns True on success, False on failure.
    """
    if recipients is None:
        recipients = config.EMAIL_RECIPIENTS

    if not recipients:
        print("  [WARNING] No email recipients configured — skipping email")
        return False

    if not config.EMAIL_SENDER or not config.EMAIL_PASSWORD:
        print("  [WARNING] Email credentials not configured — skipping email")
        return False

    if subject is None:
        period    = kpis.get("period_end", datetime.today().strftime("%d %b %Y"))
        subject   = f"[MIS Report] {config.COMPANY_NAME} — Week ending {period}"

    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"]    = config.EMAIL_SENDER
    msg["To"]      = ", ".join(recipients)

    # Plain text + HTML parts
    plain = _build_email_body(kpis, commentary, risk_flags)
    html  = _build_html_body(kpis, commentary, risk_flags)
    msg.attach(MIMEText(plain, "plain"))
    msg.attach(MIMEText(html,  "html"))

    # Attach the Excel report
    if attachment_path and os.path.exists(attachment_path):
        with open(attachment_path, "rb") as f:
            part = MIMEBase("application", "octet-stream")
            part.set_payload(f.read())
        encoders.encode_base64(part)
        part.add_header(
            "Content-Disposition",
            f"attachment; filename={os.path.basename(attachment_path)}"
        )
        msg.attach(part)
        print(f"  Attached: {os.path.basename(attachment_path)}")
    else:
        print(f"  [WARNING] Attachment not found: {attachment_path}")

    # Send
    try:
        with smtplib.SMTP(config.SMTP_HOST, config.SMTP_PORT) as server:
            server.ehlo()
            server.starttls()
            server.login(config.EMAIL_SENDER, config.EMAIL_PASSWORD)
            server.sendmail(config.EMAIL_SENDER, recipients, msg.as_string())
        print(f"  Email sent to: {', '.join(recipients)}")
        return True
    except Exception as e:
        print(f"  [ERROR] Email failed: {e}")
        return False
